### ISSUE TITLE
libxml2 is missing

### ISSUE THREAD

**Issue by nmccready** [3scale/3scale_ws_api_for_python#14]
```
    import ThreeScalePY
  File "/Users/nem/.pyenv/versions/2.7.8/lib/python2.7/site-packages/ThreeScalePY.py", line 69, in <module>
    import libxml2
```

This is not install correctly via pip on OSX. Also will this work on heroku?
in pip requirements.txt
`git+git://github.com/3scale/3scale_ws_api_for_python.git`

Using pyenv, python 2.7.8 .

**Comment by advance512** [comment]
@vdel26, how is your hunt for ways to avoid this happening going..?
The PyPI version requires libxml2, not fun.

**Comment by nmccready** [comment]
@hornedbull I'll have to get back to you as I have not been in this code for a while.

**Comment by vdel26** [comment]
@advance512 @nmccready in this other branch https://github.com/3scale/3scale_ws_api_for_python/tree/lxml I have replaced libxml2 by lxml, which causes way less trouble when installing and is also more up to date. It's nearly done, I will let you know here when it is ready.

**Comment by nmccready** [comment]
@hornedbull 
I solved via bash / shell scripting and bower. I love bower :)
Basiclaly add 3scale_ws_api_for_python as a bower dependency pointing to its git repo.

`"3scale_ws_api_for_python": "http://github.com/3scale/3scale_ws_api_for_python/archive/82328aa8e7d43f7ef89e420921a4d63e025b527f.zip"`

Then traverse the directory structure and install 3Scale via brute force. This worked on Heroku and locally.

```
if [[ $IS_HEROKU = 1 ]]; then
  cd ./bower_components/3scale_ws_api_for_python
  pip install -r requirements.txt
  python setup.py install
fi
```

**Comment by vdel26** [comment]
@hornedbull @nmccready the new version of the package where we migrated to lxml is ready. If you run `pip install ThreeScalePY` you will already get the updated version.

**Comment by nmccready** [comment]
:+1: cool ill try it out

**Comment by hornedbull** [comment]
Great. Thank you
